# This dockerfile uses the ubuntu image
# VERSION 2 - EDITION 1
# Author: docker_user
# Command format: Instruction [arguments / command] ..
 
# Base image to use, this must be set as the first line
FROM ubuntu
 
# Maintainer: docker_user <docker_user at email.com> (@docker_user)
MAINTAINER eharry eharry@foxmail.com
 
# Commands to update the image
RUN apt-get update ;

#RUN apt-get -y install build-essential htop vim python gdb ctags cscope screen tmux \
#autoconf automake libtool cmake zlib1g-dev pkg-config libssl-dev \
#git subversion snappy wget axel zsh curl

#RUN openjdk-8-jdk maven libsnappy-dev 
# http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz
 
# Commands when creating a new container
CMD /bin/bash
