apt -y install build-essential 
apt -y install htop 
apt -y install vim 
apt -y install python 
apt -y install gdb 
apt -y install ctags 
apt -y install cscope 
apt -y install screen 
apt -y install tmux
apt -y install autoconf 
apt -y install automake 
apt -y install libtool 
apt -y install cmake 
apt -y install zlib1g-dev 
apt -y install pkg-config 
apt -y install libssl-dev
apt -y install git 
apt -y install subversion 
apt -y install snappy 
apt -y install wget 
apt -y install axel 
apt -y install zsh 
apt -y install curl 
apt -y install ssh
apt -y install libaio1
apt -y install net-tools 
apt -y install inetutils-ping 
apt -y install expect
apt -y install sudo
apt -y install aptitude
apt -y install libboost-filesystem-dev 
apt -y install libboost-program-options-dev 
apt -y install libboost-system-dev 
apt -y install libboost-thread-dev

