# This dockerfile uses the ubuntu image
# VERSION 2 - EDITION 1
# Author: docker_user
# Command format: Instruction [arguments / command] ..
 
# Base image to use, this must be set as the first line
FROM ubuntu
 
# Maintainer: docker_user <docker_user at email.com> (@docker_user)
MAINTAINER eharry eharry@foxmail.com
 
# Commands to update the image
RUN rm -rf /etc/apt/sources.list; \
touch /etc/apt/sources.list; \
echo "deb http://mirrors.aliyun.com/ubuntu/ xenial main restricted universe multiverse" >> /etc/apt/sources.list ; \
echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-security main restricted universe multiverse" >> /etc/apt/sources.list ; \
echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-updates main restricted universe multiverse" >> /etc/apt/sources.list ; \
echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-proposed main restricted universe multiverse" >> /etc/apt/sources.list ; \
echo "deb http://mirrors.aliyun.com/ubuntu/ xenial-backports main restricted universe multiverse" >> /etc/apt/sources.list ; \
echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial main restricted universe multiverse" >> /etc/apt/sources.list ; \
echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial-security main restricted universe multiverse" >> /etc/apt/sources.list ; \
echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial-updates main restricted universe multiverse" >> /etc/apt/sources.list ; \
echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial-proposed main restricted universe multiverse" >> /etc/apt/sources.list ; \
echo "deb-src http://mirrors.aliyun.com/ubuntu/ xenial-backports main restricted universe multiverse" >> /etc/apt/sources.list ; \
cat /etc/apt/sources.list ; \
apt-get update ; \
apt-get -y install git curl wget xz-utils ; 
#RUN cd /tmp
#RUN wget https://npm.taobao.org/mirrors/node/v8.6.0/node-v8.6.0-linux-x64.tar.xz
#RUN xd -d node-v8.6.0-linux-x64.tar.xz
#RUN tar -xvf node-v8.6.0-linux-x64.tar
#RUN mv /tmp/node-v8.6.0-linux-x64/ /usr/local/bin/
#RUN ln -sf /usr/local/bin/node-v8.6.0-linux-x64/bin/node /usr/local/bin/node
#RUN ln -sf /usr/local/bin/node-v8.6.0-linux-x64/bin/npm /usr/local/bin/npm
#RUN npm config set user 0
#RUN npm config set unsafe-perm true
#RUN npm install -g hexo-cli
#RUN ln -sf /usr/local/bin/node-v8.6.0-linux-x64/bin/hexo /usr/local/bin/hexo

 
# Commands when creating a new container
CMD /bin/bash
