# This dockerfile uses the ubuntu image
# VERSION 2 - EDITION 1
# Author: docker_user
# Command format: Instruction [arguments / command] ..
 
# Base image to use, this must be set as the first line
FROM eharry/ubuntu_base:001
 
# Maintainer: docker_user <docker_user at email.com> (@docker_user)
MAINTAINER eharry eharry@foxmail.com
 
# Commands to update the image
RUN useradd eharry; sed -i 's|/home/eharry:|/home/eharry:/bin/bash|g' /etc/passwd

RUN apt install -y sudo net-tools ssh inetutils-ping expect

RUN echo "root:root" | chpasswd; echo "eharry:wabjtam" | chpasswd; groupadd admin; usermod -a -G admin eharry;


RUN apt install -y zsh


 
# Commands when creating a new container
CMD /bin/bash
